ai_content_strategy.settings:
  type: config_object
  label: 'AI Content Strategy Settings'
  mapping:
    system_prompt:
      type: text
      label: 'System prompt'

ai_content_strategy.prompts:
  type: config_object
  label: 'AI Content Strategy Prompts'
  mapping:
    content_strategy:
      type: mapping
      label: 'Content Strategy Prompts'
      mapping:
        prompt_template:
          type: text
          label: 'Main prompt template'
        schema_example:
          type: text
          label: 'Schema example'
    generate_more:
      type: mapping
      label: 'Generate More Ideas Prompts'
      mapping:
        prompt_template:
          type: text
          label: 'Generate more prompt template'

ai_content_strategy.recommendation_category.*:
  type: config_entity
  label: 'Recommendation Category'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    weight:
      type: integer
      label: 'Weight'
    status:
      type: boolean
      label: 'Enabled'
    instructions:
      type: text
      label: 'AI Instructions'
